### ISSUE TITLE
Avoid config completely

### ISSUE THREAD

**Issue by nothke** [stefanmielke/shakedown-rally-loader#1]
In the latest Shakedown Rally version (as of v24), I've added an ability to load cars and tracks through CLI commands directly.
So for example `NEngine-drive.exe -car "path/to/mycar.car.ini" -map "path/to/mymap.car.ini"` will directly load mycar and mymap, overriding the config `car=` and `map=` parameters, so saving to a config can be completely avoided.

**Comment by stefanmielke** [comment]
Change released on version 1.1.
